name: "Scheduler Jobs Bot"

on:
  workflow_dispatch:
  schedule:
    - cron: "10 23 * * *"
env:
  NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
  DATABASE_ID: ${{ secrets.DATABASE_ID }}
  GFW_USERNAME: ${{ secrets.GFW_USERNAME }}
  GFW_PWD: ${{ secrets.GFW_PWD }}
  GFW_URL: ${{ secrets.GFW_URL }}
  BARK_KEY: ${{ secrets.BARK_KEY }}

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4.1.7 
      - name: "Setup Node.js environment"
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
      - name: "install dependencies"
        run: npm i
      - name: "executing jobs"
        run: npm run serve
      - name: "update log and commit"
        run: npm run update
