name: "Scheduler Jobs Bot"

on:
  workflow_dispatch:
  schedule:
    - cron: "10 23 * * *"
env:
  NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
  DATABASE_ID: ${{ secrets.DATABASE_ID }}
  GFW_USERNAME: ${{ secrets.GFW_USERNAME }}
  GFW_USERNAME_2: ${{ secrets.GFW_USERNAME_2 }}
  GFW_USERNAME_3: ${{ secrets.GFW_USERNAME_3 }}
  GFW_PWD: ${{ secrets.GFW_PWD }}
  GFW_PWD_2: ${{ secrets.GFW_PWD_2 }}
  GFW_PWD_3: ${{ secrets.GFW_PWD_3 }}
  GFW_URL: ${{ secrets.GFW_URL }}
  BARK_KEY: ${{ secrets.BARK_KEY }}

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4.1.7 

      - name: "Setup Node.js environment"
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20

      - name: "Debug cache keys"
        run: |
          echo "Node.js Cache Key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}"
          echo "Playwright Cache Key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}"

      - name: "Check Node.js modules path"
        run: ls -al node_modules || echo "node_modules not found"

      - name: "Check Playwright cache path"
        run: ls -al ~/.cache/ms-playwright || echo "Playwright cache not found"

      - name: "Cache Node.js modules"
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: "Cache Playwright browsers"
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: "Install dependencies"
        run: npm ci

      - name: "Check Node.js modules path after install"
        run: ls -al node_modules

      - name: "Install Playwright browsers"
        run: npx playwright install --with-deps

      - name: "Check Playwright cache path after install"
        run: ls -al ~/.cache/ms-playwright

      - name: "Executing jobs"
        run: npm run serve

      - name: "Update log and commit"
        run: npm run update