name: "Update Commit Bot"

on:
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout codes"
        uses: actions/checkout@v3
      - name: "Setup Node.js environment"
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: "update log and commit"
        run: npm run update
